import React from 'react';
import { 
  Zap, Trash2, Sword, User, Shield, Target, Swords, Flame, Clock, Skull, MapPin, Music, Volume2 
} from 'lucide-react';

export const CHARACTERS = [
  { id: 'homer', name: 'Homer Simpson', faction: 'Simpsons', img: '/images/homer_generic_sf_1778417069953.png', color: 'from-yellow-400 to-orange-500', voice: 'Enceladus', voiceStyle: 'idiot' },
  { id: 'bart', name: 'Bart Simpson', faction: 'Simpsons', img: '/images/bart_generic_sf_1778417084932.png', color: 'from-orange-500 to-red-500', voice: 'Zephyr', voiceStyle: 'enfant' },
  { id: 'adele', name: 'Mortelle Adèle', faction: 'Cartoon', img: '/images/adele_generic_sf_1778417097290.png', color: 'from-red-600 to-purple-800', voice: 'Erinome', voiceStyle: 'enfant_diabolique' },
  { id: 'steve', name: 'Steve', faction: 'Minecraft', img: '/images/steve_sf_1778417051770.png', color: 'from-green-700 to-emerald-900', voice: 'Umbriel', voiceStyle: 'gamer' },
  { id: 'franklin', name: 'Franklin', faction: 'GTA', img: '/images/franklin_sf_1778417110721.png', color: 'from-emerald-800 to-black', voice: 'Sadachbia', voiceStyle: 'gangster' },
  { id: 'papa', name: 'Papa', faction: 'Family', img: '/images/papa_sf_1778417131723.png', color: 'from-blue-800 to-indigo-900', voice: 'Fenrir', voiceStyle: 'papa' },
  { id: 'maman', name: 'Maman', faction: 'Family', img: '/images/maman_sf_1778417144541.png', color: 'from-pink-600 to-purple-600', voice: 'Leda', voiceStyle: 'maman' },
  { id: 'clara', name: 'Clara', faction: 'Family', img: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=400&h=600&fit=crop', color: 'from-purple-500 to-fuchsia-700', voice: 'Despina', voiceStyle: 'ado_fille' },
  { id: 'mayron', name: 'Mayron', faction: 'Family', img: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=600&fit=crop', color: 'from-cyan-500 to-blue-700', voice: 'Puck', voiceStyle: 'ado_garcon' },
  { id: 'chat', name: 'Le Chat', faction: 'Animals', img: '/images/le_chat_sf_1778416951561.png', color: 'from-gray-800 to-black', voice: 'Zephyr', voiceStyle: 'animal' },
  { id: 'voisin', name: 'Le Voisin Relou', faction: 'Banlieue', img: '/images/voisin_relou_street_fighter_1778416835801.png', color: 'from-gray-400 to-gray-600', voice: 'Gacrux', voiceStyle: 'raleur' },
  { id: 'livreur', name: 'Livreur UberEats', faction: 'Précaire', img: '/images/livreur_ubereats_sf_1778416904964.png', color: 'from-green-500 to-green-700', voice: 'Umbriel', voiceStyle: 'presse' },
  { id: 'influenceuse', name: 'Influenceuse Drama', faction: 'Réseaux', img: '/images/influenceuse_drama_sf_1778416919814.png', color: 'from-pink-400 to-pink-600', voice: 'Autonoe', voiceStyle: 'drama_queen' },
  { id: 'banquier', name: 'Le Banquier', faction: 'Capitalisme', img: '/images/le_banquier_sf_1778416934105.png', color: 'from-slate-700 to-slate-900', voice: 'Orus', voiceStyle: 'autoritaire' },
  { id: 'tonton', name: 'Tonton Bourré', faction: 'Family', img: '/images/tonton_bourre_sf_1778416951155.png', color: 'from-amber-600 to-orange-800', voice: 'Iapetus', voiceStyle: 'ivre' },
  { id: 'rick', name: 'Rick Sanchez', faction: 'Sci-Fi', img: '/images/rick_sf.png', color: 'from-cyan-400 to-blue-600', voice: 'Rasalgethi', voiceStyle: 'scientifique_fou' },
  { id: 'morty', name: 'Morty Smith', faction: 'Sci-Fi', img: '/images/morty_sf.png', color: 'from-yellow-300 to-yellow-500', voice: 'Puck', voiceStyle: 'nerveux' },
  { id: 'goku', name: 'Son Goku', faction: 'Anime', img: '/images/goku_sf.png', color: 'from-orange-400 to-blue-600', voice: 'Fenrir', voiceStyle: 'guerrier' },
  { id: 'pikachu', name: 'Pikachu', faction: 'Pokemon', img: '/images/pikachu_sf.png', color: 'from-yellow-400 to-yellow-600', voice: 'Zephyr', voiceStyle: 'creature' },
  { id: 'john_wick', name: 'John Wick', faction: 'Action', img: '/images/johnwick_sf.png', color: 'from-gray-700 to-black', voice: 'Charon', voiceStyle: 'froid' },
  { id: 'shrek', name: 'Shrek', faction: 'Fantasy', img: '/images/shrek_sf.png', color: 'from-green-500 to-lime-700', voice: 'Enceladus', voiceStyle: 'ogre' },
  { id: 'lara', name: 'Lara Croft', faction: 'Adventure', img: '/images/lara_sf.png', color: 'from-brown-500 to-gray-800', voice: 'Kore', voiceStyle: 'aventuriere' },
  { id: 'walter', name: 'Walter White', faction: 'Drama', img: '/images/walter_sf.png', color: 'from-yellow-600 to-slate-900', voice: 'Orus', voiceStyle: 'menacant' },
  { id: 'spiderman', name: 'Spider-Man', faction: 'Marvel', img: '/images/spiderman_sf.png', color: 'from-red-600 to-blue-800', voice: 'Umbriel', voiceStyle: 'hero_jeune' },
  { id: 'mercredi', name: 'Mercredi Addams', faction: 'Gothic', img: '/images/mercredi_sf.png', color: 'from-gray-900 to-black', voice: 'Aoede', voiceStyle: 'monotone' },
  { id: 'denis_survivor', name: 'Denis le Survivant', faction: 'TV', img: '/images/denis_survivor_sf.png', color: 'from-orange-500 to-red-700', voice: 'Sadachbia', voiceStyle: 'autoritaire' },
  { id: 'mme_monique', name: 'Mme Monique', faction: 'Éducation', img: '/images/mme_monique_sf.png', color: 'from-blue-600 to-indigo-900', voice: 'Leda', voiceStyle: 'raleur' },
  { id: 'luffy_gear5', name: 'Luffy Gear 5', faction: 'Anime', img: '/images/luffy_gear5_sf.png', color: 'from-yellow-200 to-slate-100', voice: 'Zephyr', voiceStyle: 'hero_jeune' },
  { id: 'gilet_jaune', name: 'Didier la Manif', faction: 'Politique', img: '/images/gilet_jaune_sf.png', color: 'from-yellow-400 to-yellow-600', voice: 'Gacrux', voiceStyle: 'raleur' },
  { id: 'jul_alien', name: 'L\'Alien de Marseille', faction: 'Musique', img: '/images/jul_alien_sf.png', color: 'from-blue-400 to-cyan-600', voice: 'Sadachbia', voiceStyle: 'gangster' },
  { id: 'rat_gouttiere', name: 'Rat d\'Égout', faction: 'Cuisine', img: '/images/rat_gouttiere_sf.png', color: 'from-gray-600 to-gray-800', voice: 'Puck', voiceStyle: 'creature' },
  { id: 'asterix', name: 'Astérix', faction: 'Gaulois', img: '/images/asterix_sf_1778507330984.png', color: 'from-yellow-400 to-red-600', voice: 'Zephyr', voiceStyle: 'hero_jeune' },
  { id: 'obelix', name: 'Obélix', faction: 'Gaulois', img: '/images/obelix_sf_1778507345126.png', color: 'from-blue-400 to-white', voice: 'Enceladus', voiceStyle: 'ogre' },
  { id: 'panoramix', name: 'Panoramix', faction: 'Gaulois', img: '/images/panoramix_sf_1778507359002.png', color: 'from-green-600 to-white', voice: 'Orus', voiceStyle: 'scientifique_fou' },
  { id: 'idefix', name: 'Idéfix', faction: 'Animals', img: '/images/idefix_sf_1778507370301.png', color: 'from-white to-gray-300', voice: 'Zephyr', voiceStyle: 'creature' },
  { id: 'abraracourcix', name: 'Abraracourcix', faction: 'Gaulois', img: '/images/abraracourcix_sf_1778507384450.png', color: 'from-red-600 to-yellow-500', voice: 'Fenrir', voiceStyle: 'autoritaire' },
  { id: 'falbala', name: 'Falbala', faction: 'Gaulois', img: '/images/falbala_sf_1778507397913.png', color: 'from-pink-300 to-blue-400', voice: 'Leda', voiceStyle: 'aventuriere' },
  { id: 'cesar', name: 'Jules César', faction: 'Romain', img: '/images/cesar_sf_1778507411380.png', color: 'from-red-800 to-yellow-600', voice: 'Orus', voiceStyle: 'menacant' },
  { id: 'assurancetourix', name: 'Assurancetourix', faction: 'Gaulois', img: '/images/assurancetourix_sf_1778507427239.png', color: 'from-blue-600 to-red-500', voice: 'Zephyr', voiceStyle: 'drama_queen' },
  { id: 'cetautomatix', name: 'Cétautomatix', faction: 'Gaulois', img: '/images/cetautomatix_sf_1778507441190.png', color: 'from-orange-700 to-gray-800', voice: 'Iapetus', voiceStyle: 'guerrier' },
  { id: 'bonemine', name: 'Bonemine', faction: 'Gaulois', img: '/images/bonemine_sf_1778507453133.png', color: 'from-pink-600 to-red-700', voice: 'Autonoe', voiceStyle: 'raleur' },
  // Ma Premiere Aventure - Batch 1
  { id: 'lina', name: 'Lina la bagarreuse', faction: 'Dragon', img: '/images/lina_dragon_sf_1778750600855.png', color: 'from-red-500 to-orange-600', voice: 'Kore', voiceStyle: 'aventuriere' },
  { id: 'sachat', name: 'Sachat le chapardeur', faction: 'Dragon', img: '/images/sachat_dragon_sf_1778750623043.png', color: 'from-blue-400 to-indigo-600', voice: 'Zephyr', voiceStyle: 'enfant' },
  { id: 'timon', name: 'Timon le magicien', faction: 'Dragon', img: '/images/timon_dragon_sf_1778750639387.png', color: 'from-purple-500 to-blue-700', voice: 'Orus', voiceStyle: 'scientifique_fou' },
  { id: 'manta', name: 'La Manta', faction: 'Atlantide', img: '/images/manta_atlantide_sf_1778750654619.png', color: 'from-cyan-400 to-blue-600', voice: 'Leda', voiceStyle: 'aventuriere' },
  { id: 'behemoth', name: 'Le Béhémoth', faction: 'Atlantide', img: '/images/behemoth_atlantide_sf_1778750667383.png', color: 'from-slate-600 to-gray-800', voice: 'Fenrir', voiceStyle: 'autoritaire' },
  { id: 'espadon', name: 'L’Espadon', faction: 'Atlantide', img: '/images/espadon_atlantide_sf_1778750693942.png', color: 'from-teal-400 to-emerald-600', voice: 'Sadachbia', voiceStyle: 'presse' },
  // Ma Premiere Aventure - Batch 2
  { id: 'gloub', name: 'Gloub le mécanicien', faction: 'Phobos', img: '/images/gloub_phobos_sf_1778751038385.png', color: 'from-green-400 to-lime-600', voice: 'Enceladus', voiceStyle: 'idiot' },
  { id: 'eclipse', name: 'Eclipse la pilote', faction: 'Phobos', img: '/images/eclipse_phobos_sf_1778751057106.png', color: 'from-blue-500 to-indigo-700', voice: 'Kore', voiceStyle: 'aventuriere' },
  { id: 'toby', name: 'Toby le scientifique', faction: 'Phobos', img: '/images/toby_phobos_sf_1778751069886.png', color: 'from-yellow-400 to-orange-600', voice: 'Umbriel', voiceStyle: 'gamer' },
  { id: 'sumai', name: 'Sumaï le cueilleur', faction: 'Terre Ocre', img: '/images/sumai_ocre_sf_1778751086869.png', color: 'from-amber-500 to-orange-700', voice: 'Zephyr', voiceStyle: 'enfant' },
  { id: 'mailune', name: 'Maïlune la chasseuse', faction: 'Terre Ocre', img: '/images/mailune_ocre_sf_1778751100541.png', color: 'from-red-600 to-brown-800', voice: 'Leda', voiceStyle: 'aventuriere' },
  { id: 'issa', name: 'Issa la bergère', faction: 'Terre Ocre', img: '/images/issa_ocre_sf_1778751113697.png', color: 'from-green-500 to-teal-700', voice: 'Leda', voiceStyle: 'maman' },
  // Ma Premiere Aventure - Batch 3 & Remaining
  { id: 'bipbop', name: 'Bip-Bop', faction: 'Course', img: '/images/bipbop_sf_1778751200923.png', color: 'from-blue-400 to-cyan-600', voice: 'Zephyr', voiceStyle: 'enfant' },
  { id: 'ambrose', name: 'Ambrose', faction: 'Course', img: '/images/ambrose_sf_1778751213305.png', color: 'from-gray-700 to-slate-900', voice: 'Fenrir', voiceStyle: 'autoritaire' },
  { id: 'haru', name: 'Haru l\'éclair', faction: 'Course', img: '/images/luffy_gear5_sf.png', color: 'from-red-500 to-red-700', voice: 'Puck', voiceStyle: 'hero_jeune' },
  { id: 'bizzcotte', name: 'Bizzcotte', faction: 'Abeille', img: '/images/bonemine_sf_1778507453133.png', color: 'from-yellow-400 to-black', voice: 'Kore', voiceStyle: 'aventuriere' },
  { id: 'bizzou', name: 'Bizzou', faction: 'Abeille', img: '/images/adele_generic_sf_1778417097290.png', color: 'from-yellow-500 to-orange-600', voice: 'Leda', voiceStyle: 'enfant_diabolique' },
  { id: 'zoe', name: 'Zoé la souris', faction: 'Détective', img: '/images/rat_gouttiere_sf.png', color: 'from-gray-400 to-pink-200', voice: 'Zephyr', voiceStyle: 'enfant' },
  { id: 'jeppy', name: 'Jeppy l\'Ours', faction: 'Détective', img: '/images/shrek_sf.png', color: 'from-brown-600 to-orange-800', voice: 'Enceladus', voiceStyle: 'ogre' },
  { id: 'nouky', name: 'Nouky le raton', faction: 'Détective', img: '/images/le_chat_sf_1778416951561.png', color: 'from-slate-500 to-black', voice: 'Puck', voiceStyle: 'gangster' },
  { id: 'aivy', name: 'Aïvy', faction: 'Montagne', img: '/images/lara_sf.png', color: 'from-emerald-500 to-green-700', voice: 'Leda', voiceStyle: 'aventuriere' },
  { id: 'will', name: 'Will la débrouille', faction: 'Montagne', img: '/images/steve_sf_1778417051770.png', color: 'from-blue-600 to-indigo-800', voice: 'Umbriel', voiceStyle: 'gamer' },
  { id: 'lilon', name: 'Lilon l\'elfe', faction: 'Magie', img: '/images/spiderman_sf.png', color: 'from-cyan-300 to-blue-500', voice: 'Zephyr', voiceStyle: 'hero_jeune' },
  { id: 'camille', name: 'Camille l\'ensorceleuse', faction: 'Magie', img: '/images/mercredi_sf.png', color: 'from-purple-600 to-black', voice: 'Aoede', voiceStyle: 'monotone' },
  { id: 'lucien', name: 'Lucien le pyromancien', faction: 'Magie', img: '/images/goku_sf.png', color: 'from-red-600 to-orange-500', voice: 'Fenrir', voiceStyle: 'guerrier' },
  { id: 'sam_matou', name: 'Sam le matou', faction: 'Théâtre', img: '/images/le_chat_sf_1778416951561.png', color: 'from-orange-400 to-amber-600', voice: 'Zephyr', voiceStyle: 'enfant' },
  { id: 'pattie', name: 'Pattie', faction: 'Théâtre', img: '/images/adele_generic_sf_1778417097290.png', color: 'from-pink-400 to-rose-600', voice: 'Kore', voiceStyle: 'aventuriere' },
  { id: 'ptit_bouh', name: 'P\'tit Bouh', faction: 'Fantôme', img: '/images/mercredi_sf.png', color: 'from-blue-100 to-slate-300', voice: 'Umbriel', voiceStyle: 'nerveux' },
  { id: 'lepine', name: 'L\'Épine', faction: 'Superopolis', img: '/images/spiderman_sf.png', color: 'from-green-600 to-emerald-800', voice: 'Autonoe', voiceStyle: 'aventuriere' },
  { id: 'boombox', name: 'Boom-Box', faction: 'Superopolis', img: '/images/franklin_sf_1778417110721.png', color: 'from-yellow-600 to-orange-800', voice: 'Sadachbia', voiceStyle: 'gangster' },
];

export const ARENAS = [
  { id: 'living_room', name: 'Le Salon de la Maison', img: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=1200' },
  { id: 'springfield', name: 'Springfield Centrale', img: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200' },
  { id: 'los_santos', name: 'Rues de Los Santos', img: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=1200' },
  { id: 'nether', name: 'Le Nether', img: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200' },
  { id: 'pmu', name: 'Le PMU du Coin', img: '/images/pmu_du_coin_sf_1778416966206.png' },
  { id: 'parking', name: 'Parking du Supermarché', img: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=1200' },
  { id: 'caf', name: 'File d\'Attente de la CAF', img: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1200' },
  { id: 'space', name: 'Station Spatiale Alpha', img: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1200' },
  { id: 'cyberpunk', name: 'Neo-Tokyo 2077', img: '/images/neotokyo_sf.png' },
  { id: 'hogwarts', name: 'Poudlard', img: '/images/hogwarts_sf.png' },
  { id: 'colosseum', name: 'Colisée de Rome', img: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200' },
  { id: 'forest', name: 'Forêt Mystique', img: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200' },
  { id: 'beach', name: 'Plage de Copacabana', img: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200' },
  { id: 'boulangerie', name: 'Boulangerie Tradition', img: '/images/boulangerie_arena.png' },
  { id: 'metro_paris', name: 'Ligne 13', img: '/images/metro_paris_arena.png' },
  { id: 'plateau_tv', name: 'Le 20 Heures', img: '/images/plateau_tv_arena.png' },
  { id: 'gaulois_village', name: 'Village des Résistants', img: '/images/gaulois_village_arena.png' },
  { id: 'camp_romain', name: 'Camp de Babaorum', img: '/images/camp_romain_arena_1778507468891.png' },
  { id: 'egypte_palais', name: 'Palais de Cléopâtre', img: '/images/egypte_palais_arena_1778507482279.png' },
  { id: 'bateau_pirate', name: 'Galère des Pirates', img: '/images/bateau_pirate_arena_1778507496054.png' },
  { id: 'foret_druides', name: 'Forêt des Druides', img: '/images/foret_druides_arena_1778507514763.png' },
  { id: 'lutece', name: 'Rues de Lutèce', img: '/images/lutece_arena_1778507530787.png' },
  // Ma Premiere Aventure - Batch 1
  { id: 'foret_dragon', name: 'La Forêt du Dragon', img: '/images/foret_dragon_arena_1778750742162.png' },
  { id: 'atlantide', name: 'Cité d\'Atlantide', img: '/images/atlantide_arena_1778750773189.png' },
  { id: 'phobos_station', name: 'Station Phobos', img: '/images/phobos_arena_1778750798422.png' },
  // Ma Premiere Aventure - Remaining Arenas
  { id: 'vallee_ocre', name: 'Vallée de Terre Ocre', img: 'https://images.unsplash.com/photo-1509316785289-025f54246b21?w=1200' },
  { id: 'circuit_casse_tout', name: 'Circuit Grand Prix', img: 'https://images.unsplash.com/photo-1530906358829-e84b276e1fdd?w=1200' },
  { id: 'ruche_champ_fleuri', name: 'Ruche de Champ-Fleuri', img: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=1200' },
  { id: 'ville_superopolis', name: 'Cité de Superopolis', img: '/images/neotokyo_sf.png' },
  { id: 'bibliotheque_infinie', name: 'La Bibliothèque Infinie', img: '/images/hogwarts_sf.png' },
  { id: 'jungle_ruines', name: 'Ruines de la Jungle', img: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200' },
  { id: 'chateau_ptit_bouh', name: 'Le Château Hanté', img: 'https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=1200' },
  { id: 'montagne_dahu', name: 'Sommets Enneigés', img: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200' },
];

export const STYLE_PROMPTS: Record<string, string> = {
  idiot:             "comme un homme adulte gros et très bête qui articule mal. Voix grasse, traînante, lente. Il mâchouille ses mots et semble confus en permanence. Ton ridicule et naïf",
  enfant:            "comme un gamin insolent de 10 ans plein d'énergie. Voix aiguë, provocatrice, moqueuse. Il ricane entre ses phrases et parle vite avec un ton espiègle",
  enfant_diabolique: "comme une petite fille de 8 ans à la voix douce et mignonne, mais avec une intention sinistre qui transparaît. Elle passe d'un ton adorable à un rire inquiétant",
  gamer:             "comme un jeune gamer surexcité en plein stream. Débit rapide, voix nasillarde et énergique. Il crie les moments épiques avec enthousiasme",
  gangster:          "comme un gangster de quartier charismatique et tranquille. Voix grave, nonchalante avec une menace sous-jacente. Argot relâché, pauses calculées entre les phrases",
  papa:              "comme un père de famille protecteur et bienveillant. Voix grave, chaleureuse mais ferme. Articulation solide, ton rassurant qui peut devenir autoritaire",
  maman:             "comme une mère agacée mais aimante. Voix féminine autoritaire et pressée, avec des soupirs entre les phrases. Puis redevient douce et maternelle",
  ado_fille:         "comme une adolescente de 15 ans sarcastique qui lève les yeux au ciel. Voix chantante et traînante avec une intonation montante en fin de phrase. Ton ironique",
  ado_garcon:        "comme un adolescent de 14 ans dont la voix mue. Il alterne entre le grave et l'aigu involontairement. Un peu hésitant mais essaie d'être cool et désinvolte",
  animal:            "comme un chat agressif qui gronde et feule. Voix gutturale mélangée à des miaulements féroces et des grognements. Il crache entre les mots avec hostilité",
  raleur:            "comme un vieux Français de 60 ans qui râle sur tout. Voix sèche et traînarde. Il commence chaque phrase par un soupir agacé et marmonne avec mécontentement",
  presse:            "comme un livreur essoufflé qui court partout. Voix saccadée et précipitée avec une respiration courte audible entre les mots. Il est stressé par le temps",
  drama_queen:       "comme une influenceuse hystérique au bord des larmes. Elle exagère absolument tout. Soupirs dramatiques, voix qui tremble d'émotion et qui monte dans les aigus",
  autoritaire:       "comme un patron sévère et intransigeant. Voix grave, très articulée et sèche. Chaque mot tombe comme un verdict. Ton de commandement absolu",
  ivre:              "comme un homme complètement ivre qui bafouille. Élocution très pâteuse, les mots dérapent et se mélangent. Il perd le fil de ses phrases et hoquète",
  scientifique_fou:  "comme un génie cynique et intellectuellement supérieur. Voix légèrement éraillée, ton sarcastique et méprisant. Il parle vite et de manière condescendante",
  nerveux:           "comme un jeune homme paniqué et très anxieux. Voix tremblante et aiguë, il bégaie et hésite. Débit haché et stressé comme s'il hyperventilait",
  guerrier:          "comme un guerrier puissant en plein combat qui crie chaque attaque avec rage et puissance. Voix forte saturée d'effort et de détermination absolue",
  creature:          "comme un petit pokémon mignon qui couine. Voix très aiguë et stridente mais adorable. Il ne dit que des variations de sons mignons avec différentes émotions",
  froid:             "comme un tueur professionnel d'un calme mortel. Voix très basse, presque chuchotée, glaçante. Chaque mot est prononcé lentement avec des pauses menaçantes",
  ogre:              "comme un ogre rustique massif. Voix très grave et rauque avec un accent campagnard épais. Il rit grassement et articule de manière lourde et pesante",
  aventuriere:       "comme une exploratrice intrépide en pleine action. Voix féminine assurée et déterminée, légèrement essoufflée. Enthousiaste face au danger et à l'aventure",
  menacant:          "comme un homme dangereux et calculateur qui parle très lentement. Il articule chaque syllabe avec une menace pesante et calme qui fait froid dans le dos",
  hero_jeune:        "comme un jeune super-héros optimiste et courageux. Voix énergique, enthousiaste et brave. Ton positif et déterminé, prêt à sauver le monde",
  monotone:          "comme une jeune femme gothique au ton parfaitement plat sans aucune émotion. Aucune variation dans la voix, légèrement inquiétant par son absence totale d'affect",
};

export const STYLES = [
  { id: 'boxing', name: 'Boxe Anglaise', icon: <Zap size={16} /> },
  { id: 'griefing', name: 'Minecraft Griefing (TNT)', icon: <Trash2 size={16} /> },
  { id: 'cleaning', name: 'Ménage Express (Balai)', icon: <Sword size={16} /> },
  { id: 'brawl', name: 'GTA Brawl (Batte)', icon: <User size={16} /> },
  { id: 'sarcasm', name: 'Sarcasme Mortel', icon: <Shield size={16} /> },
  { id: 'krav_maga', name: 'Krav Maga de Comptoir', icon: <Target size={16} /> },
  { id: 'capoeira', name: 'Capoeira Foirée', icon: <Swords size={16} /> },
  { id: 'catch', name: 'Catch PMU', icon: <Flame size={16} /> },
  { id: 'bac_sable', name: 'Arts Martiaux de Bac à Sable', icon: <User size={16} /> },
  { id: 'judo_soiree', name: 'Judo de Fin de Soirée', icon: <Zap size={16} /> },
  { id: 'lutte_crocs', name: 'Lutte en Crocs', icon: <Zap size={16} /> },
  { id: 'fuite', name: 'Technique "J\'ai pas le temps"', icon: <Clock size={16} /> },
  { id: 'nerf', name: 'Tir au Pigeon (Nerf)', icon: <Target size={16} /> },
  { id: 'magie_noire', name: 'Magie Noire de Wish', icon: <Skull size={16} /> },
  { id: 'kamehameha', name: 'Kamehameha', icon: <Zap size={16} /> },
  { id: 'portal_gun', name: 'Pistolet à Portails', icon: <MapPin size={16} /> },
  { id: 'pencil', name: 'Le Crayon (John Wick)', icon: <Sword size={16} /> },
  { id: 'thunderbolt', name: 'Tonnerre (Électrique)', icon: <Zap size={16} /> },
  { id: 'dance_battle', name: 'Danse de Combat', icon: <Music size={16} /> },
  { id: 'baguette_style', name: 'Art de la Baguette', icon: <Sword size={16} /> },
  { id: 'scooter_clash', name: 'Trottinette Fury', icon: <Zap size={16} /> },
  { id: 'keyboard_bash', name: 'Guerrier du Clavier', icon: <Target size={16} /> },
  { id: 'flip_flop_fury', name: 'Lancer de Savate', icon: <Flame size={16} /> },
  { id: 'cerfa_attack', name: 'Bureaucratie Fatale', icon: <Skull size={16} /> },
  { id: 'potion_magique', name: 'Force de la Potion', icon: <Zap size={16} /> },
  { id: 'menhir_toss', name: 'Lancer de Menhir', icon: <Target size={16} /> },
  { id: 'barde_song', name: 'Chant Insupportable', icon: <Volume2 size={16} /> },
  { id: 'hammer_time', name: 'Marteau de Forgeron', icon: <Sword size={16} /> },
  { id: 'roman_punch', name: 'La Gifle Gauloise', icon: <Flame size={16} /> },
];
